config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :availability
  root 'home#index'
  resources :agents
  resources :requests do
    member do
      get 'change_status'
    end
  end
  resources :admins
  resources :properties
  resources :applicants
  resources :sessions, only: [:new, :create, :destroy]
  resources :rented

  get 'signup', to: "applicants#new", as: 'signup'
  get 'signupasagent', to: "agents#new", as: 'signupasagent'
  get 'acceptstatus', to: "requests#accept_application", as: 'acceptstatus'
  get 'rejectstatus', to: "requests#reject_application", as: 'rejectstatus'
  get 'withdrawstatus', to: "requests#withdraw_application", as: 'withdrawstatus'
  get 'waitlistacceptstatus', to: "waitlists#accept_waitlist", as: 'waitlistacceptstatus'
  get 'waitlistwithdrawstatus', to: "waitlists#withdraw_waitlist", as: 'waitlistwithdrawstatus'
  get 'waitlistrejectstatus', to: "waitlists#reject_waitlist", as: 'waitlistrejectstatus'
  get 'checkout', to: "properties#checkout", as: "checkout"
  get 'login', to: "sessions#new", as: 'login'
  get 'logingoogle', to: redirect('/auth/google_oauth2'), as: 'logingoogle'
  get 'googlelogintype', to:"sessions#googlelogintype", as: 'googlelogintype'
  get 'auth/google_oauth2/callback', to: 'sessions#googlecreate'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: "sessions#destroy", as: 'logout'
end

app/models/waitlist.rb
class Waitlist < ApplicationRecord

end

app/controllers/waitlists_controller.rb
class WaitlistsController < ApplicationController
  before_action :set_waitlist, only: %i[ show edit update destroy ]

  # GET /waitlists or /waitlists.json
  def index
    if(session[:applicant_id] != nil)
      @waitlists = Waitlist.all.where("applicant_id ="+session[:applicant_id].to_s )
    else
    @waitlists = Waitlist.all
    end
  end

  def accept_waitlist

    object = Waitlist.find(params[:request_id])
    object[:status] = "approved"
    object.save

    redirect_to waitlists_url, notice: "Waitlisted Application accepted."
  end

  def reject_waitlist
    application_object = Waitlist.find(params[:request_id])
    application_object[:status] = "rejected"
    application_object.save
    redirect_to waitlists_url, notice: "Application rejected"
  end

  def withdraw_waitlist
    application_object = Waitlist.find(params[:request_id])
    application_object[:status] = "withdraw"
    application_object.save
    redirect_to waitlists_url, notice: "Application withdrawn"
  end

  # GET /waitlists/1 or /waitlists/1.json
  def show
  end

  # GET /waitlists/new
  def new
    @waitlist = Waitlist.new
  end

  # GET /waitlists/1/edit
  def edit
  end


  def create
    @waitlist = Waitlist.new(waitlist_params)

    respond_to do |format|
      if @waitlist.save
        format.html { redirect_to @waitlist, notice: "Waitlist was successfully created." }
        format.json { render :show, status: :created, location: @waitlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @waitlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waitlists/1 or /waitlists/1.json
  def update
    respond_to do |format|
      if @waitlist.update(waitlist_params)
        format.html { redirect_to @waitlist, notice: "Waitlist was successfully updated." }
        format.json { render :show, status: :ok, location: @waitlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @waitlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waitlists/1 or /waitlists/1.json
  def destroy
    @waitlist.destroy
    respond_to do |format|
      format.html { redirect_to waitlists_url, notice: "Waitlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waitlist
      @waitlist = Waitlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def waitlist_params
      params.require(:waitlist).permit(:applicant_id, :datetime, :property_id, :status)
    end
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/waitlists/_form.html.erb
<%= form_with(model: waitlist) do |form| %>
  <% if waitlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(waitlist.errors.count, "error") %> prohibited this waitlist from being saved:</h2>

      <ul>
        <% waitlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>Continue to apply to get considered when the existing tenant moves out</p>
  <% if current_applicant %>
  <div class="field" style="display: none">
    <%= form.label :applicant_id %>
    <%= form.text_field :applicant_id, :value => current_applicant.id %>
  </div>
  <% else %>
    <div class="field">
      <%= form.label :applicant %>
      <%= form.select :applicant_id, Applicant.all.map{|c| [c.name,c.id]}%>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :datetime %>
    <%= form.date_select :datetime %>
  </div>

  <div class="field" >
    <%= form.label :property_id %>
    <%= form.number_field :property_id, :value => @waitlist.property_id.to_i %>
  </div>

  <div class="field" style="display: none">
    <%= form.label :status %>
    <%= form.text_field :status, :value => "pending" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/waitlists/edit.html.erb
<h1>Editing Waitlist</h1>

<%= render 'form', waitlist: @waitlist %>

<%= link_to 'Show', @waitlist %> |
<%= link_to 'Back', waitlists_path %>

app/views/waitlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Waitlists</h1>

<table>
  <thead>
    <tr>
      <th>Applicant</th>
      <th>Datetime</th>
      <th>Property</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waitlists.each do |waitlist| %>
      <tr>
        <td><%= Applicant.find(waitlist.applicant_id)[:name].to_s %></td>
        <td><%= waitlist.datetime %></td>
        <td><%= Property.find(waitlist.property_id)[:name].to_s %></td>
        <td><%= waitlist.status %></td>
        <% if (waitlist.status == "pending")%>
        <% if(current_agent || current_admin) %>
          <td><%= link_to 'Accept', waitlistacceptstatus_path(:request_id => waitlist.id) %></td>
          <td><%= link_to 'remove', waitlistrejectstatus_path(:request_id => waitlist.id) %></td>
        <% elsif(current_applicant) %>
          <td><%= link_to 'withdraw', waitlistwithdrawstatus_path(:request_id => waitlist.id) %></td>
        <% end %>
        <% else %>
          <% if(current_agent || current_admin) %>
            <td><p>no action</p></td>
            <td><p>no action</p></td>
          <% elsif(current_applicant) %>
            <td><p>no action</p></td>
          <% end %>
        <% end %>
        <td><%= link_to 'Show', waitlist %></td>
        <td><%= link_to 'Edit', edit_waitlist_path(waitlist) %></td>
        <td><%= link_to 'Destroy', waitlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/waitlists/new.html.erb
<h1>New Waitlist</h1>

<%= render 'form', waitlist: @waitlist %>

<%= link_to 'Back', waitlists_path %>

app/views/waitlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Applicant:</strong>
  <%= Applicant.find(@waitlist.applicant_id)[:name].to_s %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @waitlist.datetime %>
</p>

<p>
  <strong>Property:</strong>
  <%= Property.find(@waitlist.property_id)[:name].to_s %>
</p>

<p>
  <strong>Status:</strong>
  <%= @waitlist.status %>
</p>

<%= link_to 'Edit', edit_waitlist_path(@waitlist) %> |
<%= link_to 'Back', properties_path %>