config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :availability
  root 'home#index'
  resources :agents
  resources :requests do
    member do
      get 'change_status'
    end
  end
  resources :admins
  resources :properties
  resources :applicants
  resources :sessions, only: [:new, :create, :destroy]
  resources :rented

  get 'signup', to: "applicants#new", as: 'signup'
  get 'signupasagent', to: "agents#new", as: 'signupasagent'
  get 'acceptstatus', to: "requests#accept_application", as: 'acceptstatus'
  get 'rejectstatus', to: "requests#reject_application", as: 'rejectstatus'
  get 'withdrawstatus', to: "requests#withdraw_application", as: 'withdrawstatus'
  get 'waitlistacceptstatus', to: "waitlists#accept_waitlist", as: 'waitlistacceptstatus'
  get 'waitlistwithdrawstatus', to: "waitlists#withdraw_waitlist", as: 'waitlistwithdrawstatus'
  get 'waitlistrejectstatus', to: "waitlists#reject_waitlist", as: 'waitlistrejectstatus'
  get 'checkout', to: "properties#checkout", as: "checkout"
  get 'login', to: "sessions#new", as: 'login'
  get 'logingoogle', to: redirect('/auth/google_oauth2'), as: 'logingoogle'
  get 'googlelogintype', to:"sessions#googlelogintype", as: 'googlelogintype'
  get 'auth/google_oauth2/callback', to: 'sessions#googlecreate'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: "sessions#destroy", as: 'logout'
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :requests, dependent: :destroy
  has_many :waitlists, dependent: :destroy
  belongs_to :applicant, optional: true
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    property_params[:applicant_id] = nil
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def checkout
    property_object = Property.find(params[:propertyid])
    property_object[:applicant_id] = nil
    property_object.save

    Waitlist.all.select{ |x| ((x.property_id.to_i==property_object.id.to_i)&& (x.status!="rejected")&&(x.status!="withdraw"))}.each do |waitlist|
      req_object = Request.new
      req_object.property_id = property_object.id
      req_object.applicant_id = waitlist.applicant_id
      req_object.status = "pending"
      req_object.save
    end

    Waitlist.all.select{ |x| (x.property_id.to_i==property_object.id.to_i)}.each do |waitlist|
      waitlist.destroy
    end

    redirect_to properties_url, notice: "Checkout success!."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :address, :size, :start_date, :fee, :rent, :pets_allowed, :in_unit_laundry, :parking, :terms_available)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :required => 'required' %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, :required => 'required' %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size, :required => 'required' %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, :required => 'required' %>
  </div>

  <div class="field">
    <%= form.label :fee %>
    <%= form.text_field :fee, :required => 'required' %>
  </div>

  <div class="field">
    <%= form.label :rent %>
    <%= form.text_field :rent, :required => 'required' %>
  </div>

  <div class="field">
    <%= form.label :pets_allowed %>
    <%= form.check_box :pets_allowed %>
  </div>

  <div class="field">
    <%= form.label :in_unit_laundry %>
    <%= form.check_box :in_unit_laundry %>
  </div>

  <div class="field">
    <%= form.label :parking %>
    <%= form.check_box :parking %>
  </div>

  <div class="field">
    <%= form.label :terms_available %>
    <%= form.text_field :terms_available, :required => 'required' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
 <h1>Editing Property</h1>

  <%= render 'form', property: @property %>

  <%= link_to 'Show', @property %> |
  <%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        text-align: center;
        padding: 5px;
    }
</style>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Size</th>
    <th>Start date</th>
    <th>Fee</th>
    <th>Rent</th>
    <th>Pets allowed</th>
    <th>In unit laundry</th>
    <th>Parking</th>
    <th>Terms available</th>
    <th>Tenant</th>
    <th>Waitlists</th>
    <th colspan="5"></th>
  </tr>
  </thead>

  <tbody>
  <% @properties.each do |property| %>
    <tr>
      <td><%= property.name %></td>
      <td><%= property.address %></td>
      <td><%= property.size %></td>
      <td><%= property.start_date %></td>
      <td><%= property.fee %></td>
      <td><%= property.rent %></td>
      <td><%= property.pets_allowed %></td>
      <td><%= property.in_unit_laundry %></td>
      <td><%= property.parking %></td>
      <td><%= property.terms_available %></td>
      <% if property.applicant_id != nil %>
        <td><%= Applicant.find(property.applicant_id)[:name] %></td>
      <% else %>
        <td>None</td>
      <% end %>
      <td><%= Waitlist.all.select { |x| (x.property_id.to_i == property.id.to_i) }.count().to_i %></td>
      <td><%= link_to 'Show', property %></td>
      <% if current_agent || current_admin %>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if property.applicant_id != nil %>
          <td><%= link_to 'Checkout', checkout_path(propertyid: property.id) %></td>
        <% end %>
      <% end %>

      <% if property.applicant_id == nil %>
        <td><p>No occupant</p></td>
        <td><%= link_to 'Apply', new_request_url(propertyid: property.id) %></td>
        <%else%>
        <td><%= link_to 'Applywaitlist', new_waitlist_path(propertyid: property.id) %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<% if current_agent || current_admin%>
  <%= link_to 'New Property', new_property_path %>
<% end %>

app/views/properties/new.html.erb
  <h1>New Property</h1>

  <%= render 'form', property: @property %>

  <%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Size:</strong>
  <%= @property.size %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @property.start_date %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @property.fee %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @property.rent %>
</p>

<p>
  <strong>Pets allowed:</strong>
  <%= @property.pets_allowed %>
</p>

<p>
  <strong>In unit laundry:</strong>
  <%= @property.in_unit_laundry %>
</p>

<p>
  <strong>Parking:</strong>
  <%= @property.parking %>
</p>

<p>
  <strong>Terms available:</strong>
  <%= @property.terms_available %>
</p>

<% if @property.applicant_id != nil %>
  <p>
    <strong>Tenant:</strong>
    <%= Applicant.find(@property.applicant_id)[:name] %>
  </p>

<% else %>
  <% if current_applicant %>
    <p><%= link_to 'Apply', new_request_url(propertyid: @property.id) %></p>
  <% end %>
<% end %>
<% if current_agent %>
  <%= link_to 'Edit', edit_property_path(@property) %> |
<% end %>
<%= link_to 'Back', properties_path %>