config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :availability
  root 'home#index'
  resources :agents
  resources :requests do
    member do
      get 'change_status'
    end
  end
  resources :admins
  resources :properties
  resources :applicants
  resources :sessions, only: [:new, :create, :destroy]
  resources :rented

  get 'signup', to: "applicants#new", as: 'signup'
  get 'signupasagent', to: "agents#new", as: 'signupasagent'
  get 'acceptstatus', to: "requests#accept_application", as: 'acceptstatus'
  get 'rejectstatus', to: "requests#reject_application", as: 'rejectstatus'
  get 'withdrawstatus', to: "requests#withdraw_application", as: 'withdrawstatus'
  get 'waitlistacceptstatus', to: "waitlists#accept_waitlist", as: 'waitlistacceptstatus'
  get 'waitlistwithdrawstatus', to: "waitlists#withdraw_waitlist", as: 'waitlistwithdrawstatus'
  get 'waitlistrejectstatus', to: "waitlists#reject_waitlist", as: 'waitlistrejectstatus'
  get 'checkout', to: "properties#checkout", as: "checkout"
  get 'login', to: "sessions#new", as: 'login'
  get 'logingoogle', to: redirect('/auth/google_oauth2'), as: 'logingoogle'
  get 'googlelogintype', to:"sessions#googlelogintype", as: 'googlelogintype'
  get 'auth/google_oauth2/callback', to: 'sessions#googlecreate'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: "sessions#destroy", as: 'logout'
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/agent.rb
class Agent < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  def self.find_or_create_from_auth_hash(auth)
    where(name: auth.info.first_name, email: auth.info.email).first_or_initialize.tap do |agent|
      agent.name = auth.info.first_name
      agent.email = auth.info.email
      agent.phone = "87878"
      agent.password = (0...8).map { (65 + rand(26)).chr }.join.to_s
      agent.save!
    end
  end
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  has_secure_password
  has_many :requests
  has_many :waitlists
  has_one :property
  validates :email, presence: true, uniqueness: true
  def self.find_or_create_from_auth_hash(auth)
    where(name: auth.info.first_name, email: auth.info.email).first_or_initialize.tap do |applicant|
      applicant.name = auth.info.first_name
      applicant.email = auth.info.email
      applicant.phone = "87878"
      applicant.password = (0...8).map { (65 + rand(26)).chr }.join.to_s
      applicant.save!
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :requests, dependent: :destroy
  has_many :waitlists, dependent: :destroy
  belongs_to :applicant, optional: true
end

app/models/request.rb
class Request < ApplicationRecord
  # enum status: {pending: 0, accepted: 1, rejected: 2}
  belongs_to :applicant
  belongs_to :property
end

app/models/waitlist.rb
class Waitlist < ApplicationRecord

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :set_admin, only: %i[ show edit update destroy ]

  # GET /admins/1/edit
  def edit
  end

  # PATCH/PUT /admins/1 or /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to root_url, notice: "Admin was successfully updated." }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_params
      params.require(:admin).permit(:name, :email, :phone, :password)
    end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  # before_action :view_agent
  skip_before_action :authorized, only: [:new, :create]
  before_action :set_agent, only: %i[ show edit update destroy ]


  # GET /agents or /agents.json
  def index
    @agents = Agent.all
  end

  # GET /agents/1 or /agents/1.json
  def show
  end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  # GET /agents/1/edit
  def edit
  end

  # POST /agents or /agents.json
  def create
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: "Agent was successfully created." }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1 or /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to @agent, notice: "Agent was successfully updated." }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1 or /agents/1.json
  def destroy
    @agent.destroy
    respond_to do |format|
      format.html { redirect_to agents_url, notice: "Agent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = Agent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agent_params
      params.require(:agent).permit(:name, :email, :password, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorized, only: [:index]

  def index
  end

end

app/controllers/rented_controller.rb
class RentedController < ApplicationController
  def index
    @properties = Property.all.where("applicant_id ="+session[:applicant_id].to_s )
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/availability_helper.rb
module AvailabilityHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/rented_helper.rb
module RentedHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/home/index.html.erb
<p id=”notice”><%= notice %></p>
<h1>Leasing Agency System</h1>
<p>Book your next apartment here!</p>

<% if current_applicant %>
  Logged in as <%= current_applicant.name %>
  <br>
  <%= link_to "View your applications", requests_path %>
  <br>
  <%= link_to "Properties occupied", rented_index_path %>
  <br>
  <%= link_to "View your waitlisted applications", waitlists_path %>
  <br>


<% elsif current_agent %>
  Logged in as <%= current_agent.name %>
  <br>
  <%= link_to "Edit Profile", edit_agent_url(current_agent) %>
  <br>
  <%= link_to "View all applications", requests_path %>
  <br>
  <%= link_to "View all waitlisted applications", waitlists_path %>
  <br>
  <%= link_to "Edit Profile", edit_agent_url(current_agent) %>
  <br>

<% elsif current_admin %>
  Logged in as <%= current_admin.name %>
  <br>
  <%= link_to "Edit Profile", edit_admin_url(current_admin) %>
  <br>
  <%= link_to "View all applicants", applicants_path %>
  <br>
  <%= link_to "View all waitlisted applications", waitlists_path %>
  <br>
  <%= link_to "View all leasing agents", agents_path %>
  <br>
  <%= link_to "View all applications", requests_path %>
  <br>
<% else %>
  <%= link_to "New Applicant", signup_path %> |
  <%= link_to "New Agent", signupasagent_path %> |
  <%= link_to "Login", login_path %>
  <br>

<% end %>

<% if current_applicant or current_admin or current_agent %>

  <br>
  <%= link_to "View all properties", properties_path %>
  <br>
  <%= link_to "View availabilities", availability_index_path %>
  <br>
  <%= link_to "Logout", logout_path %>
  <br>
<% end %>

app/views/rented/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        text-align: center;
        padding: 5px;
    }
</style>
<% if current_admin or current_agent%>
  <p>You have rented no properties</p>
<% elsif @properties.empty? %>
  <p>You rent no properties right now</p>
<% else %>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Rent</th>
    <th>Pets allowed</th>
    <th>In unit laundry</th>
    <th>Parking</th>
    <th>Action</th>
  </tr>
  </thead>

  <tbody>
  <% @properties.each do |property| %>
    <tr>
      <td><%= property.name %></td>
      <td><%= property.address %></td>
      <td><%= property.rent %></td>
      <td><%= property.pets_allowed %></td>
      <td><%= property.in_unit_laundry %></td>
      <td><%= property.parking %></td>
      <td><%= link_to 'Move out', checkout_path(propertyid: property.id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>
<br>