config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :availability
  root 'home#index'
  resources :agents
  resources :requests do
    member do
      get 'change_status'
    end
  end
  resources :admins
  resources :properties
  resources :applicants
  resources :sessions, only: [:new, :create, :destroy]
  resources :rented

  get 'signup', to: "applicants#new", as: 'signup'
  get 'signupasagent', to: "agents#new", as: 'signupasagent'
  get 'acceptstatus', to: "requests#accept_application", as: 'acceptstatus'
  get 'rejectstatus', to: "requests#reject_application", as: 'rejectstatus'
  get 'withdrawstatus', to: "requests#withdraw_application", as: 'withdrawstatus'
  get 'waitlistacceptstatus', to: "waitlists#accept_waitlist", as: 'waitlistacceptstatus'
  get 'waitlistwithdrawstatus', to: "waitlists#withdraw_waitlist", as: 'waitlistwithdrawstatus'
  get 'waitlistrejectstatus', to: "waitlists#reject_waitlist", as: 'waitlistrejectstatus'
  get 'checkout', to: "properties#checkout", as: "checkout"
  get 'login', to: "sessions#new", as: 'login'
  get 'logingoogle', to: redirect('/auth/google_oauth2'), as: 'logingoogle'
  get 'googlelogintype', to:"sessions#googlelogintype", as: 'googlelogintype'
  get 'auth/google_oauth2/callback', to: 'sessions#googlecreate'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: "sessions#destroy", as: 'logout'
end

app/models/request.rb
class Request < ApplicationRecord
  # enum status: {pending: 0, accepted: 1, rejected: 2}
  belongs_to :applicant
  belongs_to :property
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # before_action :view_application
  skip_before_action :authorized, only: [:new, :create]
  before_action :set_request, only: %i[ show edit update destroy ]

  # GET /requests or /requests.json
  def index
    if(session[:applicant_id] != nil)
      @requests = Request.all.where("applicant_id ="+session[:applicant_id].to_s )
    else
      @requests = Request.all
    end
  end

  # GET /requests/1 or /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests or /requests.json
  def create

    # request_params[:property_id] = params[:propertyid]
    # request_params[:applicant_id] = params[:applicant_id]
    puts request_params[:property_id]
    # print params[:propertyid]
    # request_params[:status] = 0
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def accept_application
    propertyid = Request.find(params[:request_id])[:property_id]
    all_requests = Request.where(property_id: propertyid)
    all_requests.each do |request|
      if request.id != params[:request_id]
        request[:status] = "rejected"
        request.save
      end
    end

    object = Request.find(params[:request_id])
    object[:status] = "approved"
    object.save

    property_object = Property.find(object.property_id)
    property_object[:applicant_id] = object.applicant_id
    property_object.save

    redirect_to requests_url, notice: "Congratulations! Application accepted."
  end

  def reject_application
    application_object = Request.find(params[:request_id])
    application_object[:status] = "rejected"
    application_object.save
    redirect_to requests_url, notice: "Application rejected"
  end

  def withdraw_application
    application_object = Request.find(params[:request_id])
    application_object[:status] = "withdraw"
    application_object.save
    redirect_to requests_url, notice: "Application withdrawn"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:status, :applicant_id, :property_id)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_with(model: request) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="display: none">
    <%= form.label :status %>
    <%= form.text_field :status, :value => "pending" %>
  </div>
  <% if current_applicant %>
    <div class="field" style="display: none">
      <%= form.label :applicant_id %>
      <%= form.number_field :applicant_id, :value => current_applicant.id %>
    </div>
  <% else %>
    <div class="field">
      <%= form.label :applicant_id %>
      <%= form.select :applicant_id, Applicant.all.map{|c| [c.name,c.id]}%>
    </div>
    <%end %>
  <% if !params[:propertyid] %>
    <div class="field">
      <%= form.label :property_id %>
      <%= form.select :property_id, Property.select{|c| c.applicant_id == nil}.map{|c| [c.name,c.id]} %>
    </div>
    <%else %>
    <div class="field" style="display: none" >
      <%= form.label :property_id %>
      <%= form.number_field :property_id, :value => params[:propertyid] %>
    </div>
  <% end %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %><% if (current_admin )%> |<%= link_to 'Back', requests_path %><% end %>

app/views/requests/index.html.erb
  <p id="notice"><%= notice %></p>

  <h1>Applications</h1>

  <table>
    <thead>
    <tr>
      <th>Applicant</th>
      <th>Property</th>
      <th>Status</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @requests.each do |request| %>
      <tr>

        <td><%= Applicant.find(request.applicant_id)[:name] %></td>
        <td><%= Property.find(request.property_id)[:name] %></td>
        <td><%= request.status %></td>
        <% if request.status == "pending" and (current_agent || current_admin)%>
          <td><%= link_to 'Accept', acceptstatus_path(:request_id => request.id) %>
            /<%= link_to 'Reject', rejectstatus_path(:request_id => request.id) %></td>
        <% elsif request.status == "pending" %>
            <td><%= link_to 'Withdraw', withdrawstatus_path(:request_id => request.id) %></td>
        <% else %>
          <td>Decision reached</td>
        <% end %>
        <td><%= link_to 'Show', request %></td>
        <% if current_admin %>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
          </tr>
    <% end %>
    </tbody>
  </table>
  <br>
<%if !current_applicant %>
    <%= link_to 'New Application', new_request_path%>
  <% end %>

app/views/requests/new.html.erb
<h1>New Application</h1>


<%= render 'form', request: @request %>

<%= link_to 'View properties list', properties_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

  <p>
    <strong>Status:</strong>
    <%= @request.status %>
  </p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back to properties', properties_path %>